spring:
  batch:
    initialize-schema: NEVER
    job:
      enabled: false
    table-prefix: CAS_BATCH_
  config:
    use-legacy-processing: true
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:}
    username: ${DB_USER:}
    password: ${DB_PASS:}
    driverClassName: org.mariadb.jdbc.Driver
  liquibase:
    database-change-log-lock-table: CAS_DATABASECHANGELOGLOCK
    database-change-log-table: CAS_DATABASECHANGELOG
    change-log: classpath:/db/changelog/db.changelog-master.yaml

app:
  runSchedule: true
  scheduleBackup: '${SCHEDULE_BACKUP:* 0/23 * * * *}'
  storageFolder: '${STORAGE_FOLDER}'
