spring:
  config:
    use-legacy-processing: true
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:jcoffee}
    username: ${DB_USER:}
    password: ${DB_PASS:}
    driverClassName: org.mariadb.jdbc.Driver

app:
  runSchedule: true
  scheduleBackup: '${SCHEDULE_BACKUP:* 0/23 * * * *}'
