spring:
  batch:
    initialize-schema: NEVER
    job:
      enabled: false
    table-prefix: '${PREFIX_TABLE_META:CAS_BATCH_}'
  config:
    use-legacy-processing: true
  liquibase:
    database-change-log-lock-table: ${PREFIX_TABLE_META:CAS_BATCH_}DATABASECHANGELOGLOCK
    database-change-log-table: ${PREFIX_TABLE_META:CAS_BATCH_}DATABASECHANGELOG
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    parameters.prefixTable: '${PREFIX_TABLE_META:CAS_BATCH_}'

# Config logger for file and console
# Location file will store on STORAGE_FOLDER/logs/backup-remote.log
# User can config log level then set LOG_LEVEL in environment.
logging:
  level:
    root: info
    com.codingandshare.dbbk: '${LOG_LEVEL:info}'
  file:
    name: '${STORAGE_FOLDER}/logs/backup-remote.log'
  pattern:
    file: '%d %p %C{1.} [%t] %m%n'
    console: '%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable'

app:
  runSchedule: true
  scheduleBackup: '${SCHEDULE_BACKUP:* 0/23 * * * *}'
  storageFolder: '${STORAGE_FOLDER}'
  retentionBackupFile: '${RETENTION_FILE_BACKUP:7}'
  gitStorage: '${GIT_STORAGE:false}'
  git:
    token: '${GIT_TOKEN}'
    gitRemoteUrl: '${GIT_REMOTE_URL}'
    gitBranch: '${GIT_BRANCH}'
    gitDir: '${GIT_DIR}'
