spring:
  config:
    use-legacy-processing: true
  profiles: mariadb-test
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.3:///test?user=root&password=&TC_INITSCRIPT=test_init_mariadb.sql
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false
    table-prefix: test.CAS_
app:
  runSchedule: false
