version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: coffee
      MYSQL_USER: coffee
      MYSQL_PASSWORD: coffee@123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  backup-service-mysql:
    image: backup-test
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      STORAGE_FOLDER: '/tmp/backup/data'
      DB_HOST: db
      DB_NAME: coffee
      DB_USER: coffee
      DB_PASS: coffee@123
    volumes:
      - /tmp/data:/tmp/backup/data
    depends_on:
      - db
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
