name: Database Backup unit test
on:
  pull_request:

jobs:
  test:
    name: Running Units Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
          brew install docker docker-machine
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run unit test
        run: ./gradlew clean check --debug
