name: Database Backup unit test
on:
  pull_request:

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run unit test
        run: ./gradlew clean check